// <auto-generated />
using System;
using HouseCalcApi.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using AppContext = HouseCalcApi.Models.AppContext;

#nullable disable

namespace HouseCalcApi.Migrations
{
    [DbContext(typeof(AppContext))]
    partial class AppContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.1");

            modelBuilder.Entity("HouseCalcApi.Models.ClientRequestId", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ContactID")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("RequestID")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ClientRequestIds");
                });

            modelBuilder.Entity("HouseCalcApi.Models.Price", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<int>("Value")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Prices");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "setwalls",
                            Value = 16000
                        },
                        new
                        {
                            Id = 2,
                            Name = "project",
                            Value = 650
                        },
                        new
                        {
                            Id = 3,
                            Name = "geologi",
                            Value = 40000
                        },
                        new
                        {
                            Id = 4,
                            Name = "geodesy",
                            Value = 15000
                        },
                        new
                        {
                            Id = 5,
                            Name = "construction",
                            Value = 5500
                        },
                        new
                        {
                            Id = 6,
                            Name = "armo",
                            Value = 300
                        },
                        new
                        {
                            Id = 7,
                            Name = "seams",
                            Value = 300
                        },
                        new
                        {
                            Id = 8,
                            Name = "delivery",
                            Value = 200
                        },
                        new
                        {
                            Id = 9,
                            Name = "fundation",
                            Value = 11500
                        },
                        new
                        {
                            Id = 10,
                            Name = "roof",
                            Value = 13500
                        },
                        new
                        {
                            Id = 11,
                            Name = "windows",
                            Value = 15500
                        },
                        new
                        {
                            Id = 12,
                            Name = "door",
                            Value = 65000
                        });
                });

            modelBuilder.Entity("HouseCalcApi.Models.UserCalculationRequest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AllCost")
                        .HasColumnType("INTEGER");

                    b.Property<int>("AreaHouseSquarMeters")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Armo")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Construction")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DateTime")
                        .HasColumnType("TEXT");

                    b.Property<int>("DeliveryDistanceKilometers")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Door")
                        .HasColumnType("INTEGER");

                    b.Property<int>("FiledWindowArea")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Fundation")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Geodesy")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Geology")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Projects")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("RequestId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Roof")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Seams")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Walls")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("UserCalculationRequests");
                });

            modelBuilder.Entity("HouseCalcApi.Models.UserContact", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("NameUser")
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneUser")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("UserContacts");
                });
#pragma warning restore 612, 618
        }
    }
}
