// <auto-generated />
using System;
using HauseCalcApi.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using AppContext = HauseCalcApi.Models.AppContext;

#nullable disable

namespace HauseCalcApi.Migrations
{
    [DbContext(typeof(AppContext))]
    [Migration("20240227202003_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.1");



            modelBuilder.Entity("HauseCalcApi.Models.SetServiceClient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AllCost")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Armo")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Construction")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DateTime")
                        .HasColumnType("TEXT");

                    b.Property<int>("DeliveryDistanceKilometers")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Door")
                        .HasColumnType("INTEGER");

                    b.Property<int>("FiledWindowArea")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Fundation")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Geodesy")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Geology")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("IdGuid")
                        .HasColumnType("TEXT");

                    b.Property<int>("Projects")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Roof")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Seams")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Walls")
                        .HasColumnType("INTEGER");

                    b.Property<int>("areaHouseSquarMeters")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("SetServiceClients");
                });
#pragma warning restore 612, 618
        }
    }
}
